version: "3.8"

services:
  # 1. Frontend Next.js
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  # 2. Backend Golang (Air Live-reload)
  backend:
    build: ./backend
    ports:
      - "8081:8080"
    volumes:
      - ./backend:/app
    # Load biến môi trường từ file .env
    env_file:
      - .env
